## 学习R

## 1. 从R中获得帮助

- 获得函数或数据集的信息，可以输入？,后面加上函数名。如果想要查找某个函数，输入两个问好(??)，后面加上与此函数相关的关键词
- help以及help.search分别等同于?及??

In [2]:
?mean

mean                   package:base                    R Documentation

_A_r_i_t_h_m_e_t_i_c _M_e_a_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generic function for the (trimmed) arithmetic mean.

_U_s_a_g_e:

     mean(x, ...)
     
     ## Default S3 method:
     mean(x, trim = 0, na.rm = FALSE, ...)
     
_A_r_g_u_m_e_n_t_s:

       x: An R object.  Currently there are methods for numeric/logical
          vectors and date, date-time and time interval objects.
          Complex vectors are allowed for 'trim = 0', only.

    trim: the fraction (0 to 0.5) of observations to be trimmed from
          each end of 'x' before the mean is computed.  Values of trim
          outside that range are taken as the nearest endpoint.

   na.rm: a logical value indicating whether 'NA' values should be
          stripped before the computation proceeds.

     ...: further arguments passed to or from other methods.

_V_a_l_u_e:

     If 'trim' is zero (the default), the arithmetic mean of the values
     in 'x' is computed, as a numeric or complex vector of length one.
     If 'x' is not logical (coerced to numeric), numeric (including
     integer) or complex, 'NA_real_' is returned, with a warning.

     If 'trim' is non-zero, a symmetrically trimmed mean is computed
     with a fraction of 'trim' observations deleted from each end
     before the mean is computed.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'weighted.mean', 'mean.POSIXct', 'colMeans' for row and column
     means.

_E_x_a_m_p_l_e_s:

     x <- c(0:10, 50)
     xm <- mean(x)
     c(xm, mean(x, trim = 0.10))

- apropos能找到匹配其输入的变量（以及函数）

In [3]:
apropos("z$")

[1] "SSgompertz" "toeplitz"   "unz"

- 查找“任何”包，可以使用RsiteSearch，它会查询整个http://search.r-project.org 网站的包
- RSeek(http://rseek.org) 是一个R的网页搜索引擎，能查找出各种函数、R邮件列表归档中的讨论和博客文章
- R博客(http://www.r-bloggers.com) 是R主要的博客社区

## 2.科学计算器

### 向量化

- 冒号运算符
- c函数

向量化的含义
- 无需显示地编写循环语句
- 能计算汇总统计

In [1]:
sum(1:5)

identical(2 ^ 3, 2 ** 3)

[1] 15

[1] TRUE

要检查两个数字是否一样，不要使用==，而使用**all.equal**函数。我们也可以使用==来比较字符串。

In [5]:
sqrt(2)^2 == 2

all.equal(sqrt(2)^2,2)

[1] FALSE

[1] TRUE

### 变量赋值

- 我们不能声明任何类型，因为在R中不存在这种概念
- 我们可以使用<-或=给变量赋值，虽然由于历史原因，<-是首先
- 我们还可以使用<<-来对全局变量赋值
- 另一种变量赋值的方法是通过assign函数赋值

赋值和打印在同一行
- 多个语句放在一行，中间用分号;分开
- 把赋值语句写在括号()中

In [2]:
assign("my_local_variable", 9 ^ 3 + 10 ^ 3)

my_local_variable

[1] 1729

In [6]:
z <- rnorm(1);z
(zz <- rlnorm(1))

[1] 0.7338516

[1] 0.631836

### 特殊数字

- Inf和-Inf, 正负无穷
- NaN, 不是一个数，意味着我们的计算或没有数学意义，或无法正确执行
- NA, 不可用，代表缺失值

### 逻辑向量

- !代表非操作
- &代表与操作
- |代表或操作

In [7]:
x <- c(TRUE, FALSE, NA)
xy <- expand.grid(x=x, y=x)
within(
    xy,
    {
        and <- x & y
        or <- x | y
        not.y <- !y
        not.x <- !x
    }
)

x     y     not.x not.y or    and  
1  TRUE  TRUE FALSE FALSE  TRUE  TRUE
2 FALSE  TRUE  TRUE FALSE  TRUE FALSE
3    NA  TRUE    NA FALSE  TRUE    NA
4  TRUE FALSE FALSE  TRUE  TRUE FALSE
5 FALSE FALSE  TRUE  TRUE FALSE FALSE
6    NA FALSE    NA  TRUE    NA FALSE
7  TRUE    NA FALSE    NA  TRUE    NA
8 FALSE    NA  TRUE    NA    NA FALSE
9    NA    NA    NA    NA    NA    NA

In [8]:
none_true <- c(FALSE, FALSE, FALSE)
some_true <- c(FALSE, TRUE, FALSE)
all_true <- c(TRUE, TRUE, TRUE)
any(none_true)
any(some_true)
all(some_true)
all(all_true)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

## 检查变量和工作区

### 类

R中所有变量都有一个类。例如大部分的数字是numeric类。可以使用**class**函数来找出变量的类名。所有的变量除了类之外，还有一个内部存储类型(通过typeof访问)、一个模式(mode)，以及一个存储模式(storage.mode)。

### 其他通用类

除了数字类和逻辑类外，向量还有其他三个类
- 用于存储文本的字符类character
- 用于存储类别数据的因子类factor
- 用于存储二进制数据的原始类raw

In [9]:
(gender <- factor(c('male', 'female', 'female', 'male', 'female')))

levels(gender)
nlevels(gender)
as.integer(gender)

[1] male   female female male   female
Levels: female male

[1] "female" "male"

[1] 2

[1] 2 1 1 2 1

### 检查和更改类

- 测试对象的类型，最好用is函数

In [10]:
is.character('red lorry, yellow lorry')
is.logical(FALSE)

# 查看在base包中所有的is函数
ls(pattern='^is', baseenv())

[1] TRUE

[1] TRUE

[1] "is.array"                "is.atomic"              
 [3] "is.call"                 "is.character"           
 [5] "is.complex"              "is.data.frame"          
 [7] "is.double"               "is.element"             
 [9] "is.environment"          "is.expression"          
[11] "is.factor"               "is.finite"              
[13] "is.function"             "is.infinite"            
[15] "is.integer"              "is.language"            
[17] "is.list"                 "is.loaded"              
[19] "is.logical"              "is.matrix"              
[21] "is.na"                   "is.na.data.frame"       
[23] "is.na.numeric_version"   "is.na.POSIXlt"          
[25] "is.na<-"                 "is.na<-.default"        
[27] "is.na<-.factor"          "is.na<-.numeric_version"
[29] "is.name"                 "is.nan"                 
[31] "is.null"                 "is.numeric"             
[33] "is.numeric.Date"         "is.numeric.difftime"    
[35] "is.numeric.POSIXt"       "is.numeric_version"     
[37] "is.object"               "is.ordered"             
[39] "is.package_version"      "is.pairlist"            
[41] "is.primitive"            "is.qr"                  
[43] "is.R"                    "is.raw"                 
[45] "is.recursive"            "is.single"              
[47] "is.symbol"               "is.table"               
[49] "is.unsorted"             "is.vector"              
[51] "isatty"                  "isBaseNamespace"        
[53] "isdebugged"              "isIncomplete"           
[55] "isNamespace"             "isNamespaceLoaded"      
[57] "isOpen"                  "isRestart"              
[59] "isS4"                    "isSeekable"             
[61] "isSymmetric"             "isSymmetric.matrix"     
[63] "isTRUE"

- 改变一个对象的类型，就是所谓的转型(casting)，尽可能使用特定的as\*函数而非单纯的as函数

In [11]:
x <- '123.456'
as.numeric(x)

[1] 123.456

### 检查变量

- print函数
- 大部分print函数的实现建立在调用底层的cat函数上
- summary函数为不同的数据类型提供汇总信息
- head函数显示前几行信息
- str函数能显示对象的结构
- 每个类都有自己的打印(print)方法，一次控制如何显示到控制台，unclass函数可用绕开这一点
- attributes函数能显示当前对象的所有属性列表
- view,edit和fix函数可以浏览和编辑数据框

### 工作区

- ls函数可列出现有变量的名称
- ls.str函数查看变量的结构
- rm函数删除变量

## 3. 向量、矩阵和数组

### 向量

创建向量
- 冒号运算符
- c函数
- vector函数

In [12]:
vector('numeric',5)

[1] 0 0 0 0 0

#### 序列

- seq函数：seq.int, seq_len(创建一个从1到它的输入值的序列), seq_along(创建一个从1开始，长度为其输入值的序列)


In [13]:
seq.int(3,12,2)

[1]  3  5  7  9 11

#### 长度

- length函数
- nchar函数

In [14]:
sn <- c('SHeena', 'leads', 'Sheila', 'needs')
length(sn)
nchar(sn)

[1] 4

[1] 6 5 6 5

#### 命名

R向量的一大特性是能给每个元素命名。你也可以在向量创建后用names函数为元素添加名字。

In [15]:
c(apple=1, banana=2, 'kiwi fruit'=3,4)

x <- 1:4
names(x) <- c('one', 'two', 'three', 'four')
names(x)

apple     banana kiwi fruit            
         1          2          3          4

[1] "one"   "two"   "three" "four"

#### 索引向量

- 索引向量用方括号[]来实现
- which函数将返回逻辑向量中为TRUE的位置

In [16]:
x <- (1:5)^2

x[c(1,3,5)]
x[c(-2,-4)]
x[c(TRUE, FALSE, TRUE, FALSE, TRUE)]

which(x > 10)
which.min(x)
which.max(x)

[1]  1  9 25

[1]  1  9 25

[1]  1  9 25

[1] 4 5

[1] 1

[1] 5

#### 向量循环和重复

- 向量和标量的运算
- rep函数，它允许我们重复使用元素来创建向量

In [17]:
1:5 + 1

rep(1:5, 3)

[1] 2 3 4 5 6

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

### 矩阵和数组

#### 创建数组和矩阵

- array函数
- matrix函数

In [18]:
(array_one <- array(1:12, dim=c(4,3)))
(matrix_one <- matrix(1:12, nrow=4))
identical(array_one, matrix_one)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[1] TRUE

#### 行、列和维度

- dim函数返回其维度的整数值向量
- nrow和ncol函数返回行数和列数
- length函数将返回所有维度的乘积

#### 行名、列名和维度名

- rownames和colnames函数返回矩阵的行名和列名

#### 索引数组

索引数组与索引向量类似

In [19]:
(a_matrix <- 
 matrix(1:12, nrow=4, dimnames=list(c('one','two','three','four'),c('ein','zwei','drei'))))

a_matrix[1,]
a_matrix[1, c('zwei','drei')]

ein zwei drei
one   1   5     9  
two   2   6    10  
three 3   7    11  
four  4   8    12

ein zwei drei 
   1    5    9

zwei drei 
   5    9

#### 合并矩阵

- c函数能在拼接矩阵之前把它们转换成向量
- cbind和rbind函数按行和列来绑定两个矩阵，能更自然地合并它们

#### 数组算术

- 标准算术运算符(+,-,\*,/)将以相同的方式按元素来处理矩阵和数组
- t函数用于转置矩阵
- 矩阵内乘和外乘运算，有特殊运算符%\*%和%o%
- 幂运算符^将作用于矩阵中的每个元素
- 求逆矩阵用solve函数

In [20]:
(m <- matrix(c(1,0,1,5,-3,1,2,4,7), nrow=3))
(inverse_of_m <- solve(m))
(m %*% inverse_of_m)

[,1] [,2] [,3]
[1,] 1     5   2   
[2,] 0    -3   4   
[3,] 1     1   7

[,1] [,2] [,3]
[1,] -25  -33  26  
[2,]   4    5  -4  
[3,]   3    4  -3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

## 4. 列表和数据框

### 列表

#### 创建列表

- 列表由list函数创建

In [21]:
(a_list <- list(
    c(1,1,2,5,14,42),
    month.abb,
    matrix(c(3,-8,1,-3), nrow=2),
    asin
)
)

[[1]]
[1]  1  1  2  5 14 42

[[2]]
 [1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

[[3]]
     [,1] [,2]
[1,]    3    1
[2,]   -8   -3

[[4]]
function (x)  .Primitive("asin")

#### 原子变量和递归变量

- 由于列表具有把其他列表包含在内的能力，它被认为是递归变量。
- 与之相对，向量、矩阵和数组则是原子变量
- is.recursive和is.atomic函数可测试它们的类型

#### 索引列表

- 与向量类似，我们可以通过方括号[]、正或负的下标数字、元素名称或逻辑索引这四种方法访问列表中的元素
- 如果要访问列表元素中的内容，可以通过[[]]
- 对于列表中的命名元素，也可以使用美元符号运算符$

In [22]:
l <- list(
    first=1,
    second=2,
    third = list(
        alpha=3.1,
        beta=3.2
    )
)

l[1:2]
l[c('first','second')]
l[c(TRUE,TRUE,FALSE)]

l[[1]]
l[['first']]

l$first

l[[c('third','beta')]]

$first
[1] 1

$second
[1] 2

$first
[1] 1

$second
[1] 2

$first
[1] 1

$second
[1] 2

[1] 1

[1] 1

[1] 1

[1] 3.2

#### 向量和列表之间的转换

- 向量可使用函数as.list函数来转换成列表
- 如果列表中每个元素都是标量值，可使用之前出现过的函数(as.numeric, as.character等)将其转换成向量

In [23]:
busy_beaver <- c(1,6,21,107)
as.list(busy_beaver)

as.numeric(list(1,6,21,107))

[[1]]
[1] 1

[[2]]
[1] 6

[[3]]
[1] 21

[[4]]
[1] 107

[1]   1   6  21 107

#### 组合列表

- c函数既能用于拼接向量，亦能用于拼接列表

### NULL

- NULL是个特殊值，它标识一个空的变量
- 在创建列表时，你可能会想指定一个元素，表明它必须存在但没有赋值
- NULL和缺失值NA之间的最大区别是，NA是一个标量值，而NULL不会占用任何空间，它的长度为零

In [24]:
is.null(NULL)

[1] TRUE

### 数据框

#### 创建数据框

- 用data.frame函数创建数据框

In [25]:
(a_data_frame <- data.frame(
    x = letters[1:5],
    y = rnorm(5),
    z = runif(5) > 0.5
))

x y           z    
1 a -0.35626139 FALSE
2 b -0.04642748 FALSE
3 c -1.03722049  TRUE
4 d  0.74940529  TRUE
5 e -0.33567867  TRUE

#### 索引数据框

- 和矩阵索引的方式一样
- 数据框子集

In [26]:
a_data_frame[2:3,-3]
a_data_frame[c(FALSE,TRUE,TRUE,FALSE,FALSE),c('x','y')]

subset(a_data_frame, y>0 | z, x)

x y          
2 b -0.04642748
3 c -1.03722049

x y          
2 b -0.04642748
3 c -1.03722049

x
3 c
4 d
5 e

#### 基本数据框操作

- 数据框可以使用cbind和rbind进行连接(join)
- 当两个数据框有相同的列时，可使用merge函数合并

## 5. 环境和函数

### 环境

- 我们所创建的所有变量都需要存储在某处，即环境
- 环境本身也是另一种类型的变量
- 通常情况下，你不需要直接与环境打交道
- 环境的创建是使用new.env函数
- 可以把环境参数传入ls和ls.str函数中，列出它的所有内容
- 可用exists函数测试变量是否在环境中
- 全局环境globalen()

In [27]:
an_environment <- new.env()
an_environment[['pythag']] <- c(12,15,20,21)
an_environment$root <- polyroot(c(6,-5,1))

ls(envir=an_environment)
ls.str(envir=an_environment)

exists('pythag',an_environment)

(a_list <- as.list(an_environment))

head(ls(envir = baseenv()),5)

[1] "pythag" "root"

pythag :  num [1:4] 12 15 20 21
root :  cplx [1:2] 2+0i 3-0i

[1] TRUE

$pythag
[1] 12 15 20 21

$root
[1] 2+0i 3-0i

[1] "-"         "-.Date"    "-.POSIXt"  "!"         "!.hexmode"

### 函数



#### 创建和调用函数

- formals函数能取得函数的参数并返回一个列表
- body函数可用于返回函数体
- R提供了一个特殊参数..., 它包括了所有不能被位置或名称匹配的参数

In [28]:
hypotenuse <- function(x, y){
    sqrt(x^2 + y^2)
}

hypotenuse(3, 4)

normalize <- function(x, m=mean(x,...), s=sd(x,...),...){
    (x-m)/s
}

normalize(c(1,3,6,10,NA), na.rm=TRUE)

[1] 5

[1] -1.0215078 -0.5107539  0.2553770  1.2768848         NA

#### 向其他函数传递和接收函数

- 函数可以像其他变量类型一样地使用，我们可将之作为其他函数的参数，并且从函数中返回。一个常见的例子是do.call函数。

In [30]:
do.call(hypotenuse,list(x=3,y=4))  # 和hypotenuse(3,4)一样

[1] 5

## 6. 字符串和因子

### 字符串

#### 创建和打印字符串

- 字符串向量可用c函数创建
- paste函数能将不同字符串组合在一起
- toString函数是paste的变种，它在打印向量时非常有用
- cat是一个低级函数，类似于paste，不过格式功能更少。很少直接调用它，但是它是大部分print函数的基础。
- noquote函数在打印到控制台时，会去掉引号

In [32]:
paste(c("red", "yellow"), "lorry")

x <- (1:15)^2
toString(x)

[1] "red lorry"    "yellow lorry"

[1] "1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225"

#### 格式化数字

- formatC函数可让你使用C语言的格式化风格
- 更通用的C风格的格式化函数sprintf函数
- 其他格式化数字的方法有format和prettyNum函数

In [37]:
pow <- 1:3
(powers_of_e <- exp(pow))

formatC(powers_of_e, digits=3)

sprintf("To three decimal places, e ^ %d = %.3f", pow, powers_of_e)

format(powers_of_e, digits=3, trim=TRUE)

prettyNum(
    c(1e10, 1e-20),
    big.mark = ",",
    small.mark = " ",
    preserve.width = "individual",
    scientific = FALSE
)

[1]  2.718282  7.389056 20.085537

[1] "2.72" "7.39" "20.1"

[1] "To three decimal places, e ^ 1 = 2.718" 
[2] "To three decimal places, e ^ 2 = 7.389" 
[3] "To three decimal places, e ^ 3 = 20.086"

[1] "2.72"  "7.39"  "20.09"

[1] "10,000,000,000"            "0.00000 00000 00000 00001"

#### 特殊字符

- 有一些特殊的字符可以被包含在字符串中，使用cat而非print函数

In [38]:
cat("foo\nbar", fill=TRUE)

foo
bar


#### 更改大小写

- 使用toupper和tolower函数

#### 截取字符串

- 使用substring和substr函数

#### 分割字符串

- 使用strsplit函数

#### 文件路径

- 使用getwd函数查看工作路径，并使用setwd函数来改变它
- 使用file.path函数来创建文件路径
- path.expand函数能将相对路径转换为绝对路径
- basename函数只返回文件名，而dirname函数只返回文件的目录

### 因子

#### 创建因子

- 使用factor函数创建

#### 更改因子水平

- 通过指定levels参数来更改因子水平
- relevel函数是另一种改变因子水平顺序的方法

#### 去掉因子水平

- 使用droplevels函数

In [44]:
getting_to_work <- data.frame(
    mode=c(
        "bike","car","bus","car","walk","bike","car","bike","car","car"
    ),
    time_mins = c(25,13,NA,22,65,28,15,24,NA,14)
)

#去掉那些time_mins是NA的行
(getting_to_work <- subset(getting_to_work, !is.na(time_mins)))

unique(getting_to_work$mode)
levels(getting_to_work$mode)

getting_to_work$mode <- droplevels(getting_to_work$mode)
levels(getting_to_work$mode)

mode time_mins
1  bike 25       
2  car  13       
4  car  22       
5  walk 65       
6  bike 28       
7  car  15       
8  bike 24       
10 car  14

[1] bike car  walk
Levels: bike bus car walk

[1] "bike" "bus"  "car"  "walk"

[1] "bike" "car"  "walk"

#### 有序因子

- 使用ordered函数
- 或通过给factor传入order=TRUE参数

In [49]:
happy_choices <- c("depressed", "grumpy", "so-so", "cheery", "ecstatic")
happy_values <- sample(happy_choices, 10000, replace=TRUE)
happy_fac <- factor(happy_values, happy_choices)
head(happy_fac)

happy_ord <- ordered(happy_values, happy_choices)
head(happy_ord)

[1] depressed cheery    grumpy    so-so     grumpy    so-so    
Levels: depressed grumpy so-so cheery ecstatic

[1] depressed cheery    grumpy    so-so     grumpy    so-so    
Levels: depressed < grumpy < so-so < cheery < ecstatic

#### 将连续变量转换为类别

- cut函数能将数值变量切成不同的块，然后返回一个因子

In [52]:
ages <- 10 + 50 * rbeta(10000,2,3)
grouped_ages <- cut(ages, seq.int(16,66,10))
table(grouped_ages)

grouped_ages
(16,26] (26,36] (36,46] (46,56] (56,66] 
   3167    3262    2175     686      15 

#### 生成因子水平

-gl函数生成因子

In [53]:
gl(3,2,labels=c("placebo", "drug A", "drug B"))

[1] placebo placebo drug A  drug A  drug B  drug B 
Levels: placebo drug A drug B

#### 合并因子

- interaction函数