# Python语言

## Python环境创建

- 下载Python软件包，点击[此处](https://www.python.org/)；或者点击[此处](https://www.anaconda.com/distribution/)

- 安装jupyter，点击[此处](https://jupyter.org/install)

## 使用Python进行多元统计分析

使用numpy包，点击[https://numpy.org/]

**习题**

设一个$n=3$的随机样本取自二维正态总体，其数据矩阵为

$$\mathbf{X}=\left[\begin{array}{cc}{6} & {9} \\ {10} & {6} \\ {8} & {3}\end{array}\right]$$

试对$\mu_{0}^{\prime}=[9,5]$计算$T^{2}$。

In [86]:
import numpy as np

x = np.matrix([[6,9], [10,6], [8,3]])
mu = np.matrix([9,5]).T

print(x)
print("\nDim of Data: ", x.shape)

print("\n", mu)
print("\nDim of Data: ", mu.shape)

[[ 6  9]
 [10  6]
 [ 8  3]]

Dim of Data:  (3, 2)

 [[9]
 [5]]

Dim of Data:  (2, 1)


求解均值向量

In [89]:
mean_x = np.mean(x, axis=0).T

print(mean_x)
print("\nDim of Data: ", mean_x.shape)

[[8.]
 [6.]]

Dim of Data:  (2, 1)


求解方差协方差矩阵$S$

In [92]:
S = np.cov(x, rowvar=False)

print(S)
print("\nDim of Data: ", S.shape)

[[ 4. -3.]
 [-3.  9.]]

Dim of Data:  (2, 2)


求解$S^{-1}$

In [95]:
inv_S = np.linalg.inv(S)

print(inv_S)
print("\nDim of Data: ", inv_S.shape)

[[0.33333333 0.11111111]
 [0.11111111 0.14814815]]

Dim of Data:  (2, 2)


计算$T^{2}$统计量

In [106]:
T2 = len(x)*(mean_x-mu).T*inv_S*(mean_x-mu)
T2

matrix([[0.77777778]])

In [108]:
T2 = len(x)*(mean_x-mu).T.dot(np.linalg.inv(np.cov(x.T))).dot(mean_x-mu)
T2

matrix([[0.77777778]])